<?php
    if (!($content instanceof Layout_Content)) {
        $content = $this->_content;
    }

    $this->topApps = $this->getApps(false);
    $this->allApps = $this->getApps(true);
//echo $content->getDoctype();
?>
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=<?php echo $content->getCharset(); ?>" />
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
        <?php
            echo $content->getHeader();
        ?>
        <title>
            <?php
                echo $content->getTitle();
            ?>
        </title>
    </head>
    <body> 
        <div>
            <div class="window ui-helper-clearfix" style="padding-left: 10px; padding-right: 10px;">
                <?php
                    echo $content->getBody();
                ?>
            </div>

            <?php
                $buttons = $content->getButtons();
                if ($buttons):
                    ?>

                    <div id="layout-footer" class="window">
                        <?php
                        echo $buttons;
                        ?>    
                    </div>

                    <?php
                endif;
            ?>
        </div>

        <script language="javascript">
            jQuery(document).ready(function () {
                jQuery(".dropdown-menu").TDropdown();
                jQuery(".ui-tabs").TTabs();
                configTabIndex();
                jQuery("input").taEscEnter();
                jQuery("select").taEscEnter();
                jQuery("button").taEsc();
<?php
    $onLoad = $content->getOnLoad();
    if (count($onLoad) > 0) {
        foreach ($onLoad as $value) {
            if (substr($value, 0, 7) == 'base64:') {
                $value = base64_decode(substr($value, 7));
            }
            echo '                ' . $value . "\n";
        }
    }
?>
            });
        </script>
    </body>
</html>