<?php
    /*$idGrid = $this->grid->getID();
    $tabs = new ZendT_View_Tabs('divTabsTarefa');
    $tabs->disableAll(false);
    $tabs->addTab('Grupos', $this->grid);
    $tabs->addTabWhereGrid('Pessoas do Grupo'
                          ,ZendT_Url::getBaseUrl().'/auth/usuario/grid'
                          ,'papel.id'
                          ,$idGrid);

    echo $tabs->render();*/

    $idGrid = $this->grid->getID();

    $tabs = new ZendT_View_Tabs('divTabsTarefa');
    $tabs->disableAll(false);
    $tabs->addTab('Grupos', $this->grid)
            ->addTabUrl('Pessoas do Grupo'
                    , new ZendT_JS_Command("function(){ "
                            . "  var url = '" . ZendT_Url::getBaseUrl() . "/auth/usuario/grid'; "
                            . "  url = url + '?id_papel=' + $('#{$idGrid}').jqGrid('getGridParam','selrow'); "
                            . "  url = url + '&typeModal=AJAX'; "
                            . "  return url; "
                            . "}"));
    echo $tabs->render();
?>